name: Minikube CI

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start Minikube
      uses: medyagh/setup-minikube@latest

    - name: Use Minikube Docker daemon
      run: |
        eval $(minikube docker-env)

    - name: Build Docker image
      run: |
        docker build -t node-app:latest .

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

    - name: Verify deployment
      run: kubectl get pods
